const fetchURL = process.env.FETCH_URL;

async function getData() {
  const res = await fetch(`${fetchURL}api/datequestion`, {
    next: { revalidate: 60 },
  });
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.

  // Recommendation: handle errors
  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function Head() {
  const question = await getData();
  const titleString = `#${question.day} ${question.hint}`;

  return (
    <>
      <title>Rockbusters</title>
      <meta
        property="og:image"
        content={`${fetchURL}api/og?title=${encodeURIComponent(titleString)}`}
      />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/karl.png" />
    </>
  );
}
